### ISSUE TITLE
A9 E4 - Migrar UI para IProdutoViewExpandido (não vai mais suportar SQLite)

### ISSUE THREAD

**Issue by RafaelEstevamReis** [DaniloOtavio/Aulas#49]

**Comment by DaniloOtavio** [comment]
* Migrar UI para IProdutoViewExpandido
* Como o SQLite não está expandido ainda, ele vai perder suporte

**Comment by DaniloOtavio** [comment]
Não há commit pois já havia migrado para IProdutoViewExpandido ao implementar as modificações na UI.
