### ISSUE TITLE
A9 E0 - Alterações para o Software

### ISSUE THREAD

**Issue by RafaelEstevamReis** [DaniloOtavio/Aulas#51]
Será implementada uma nova versão da ProdutoView
(É o que faremos na Expandida)

* Permitir Localizar produtos por Parte do Nome

**Comment by DaniloOtavio** [comment]
* Implementar na interface (IProdutoViewExpandida) função que localiza produtos por parte do nome.
* Implementar na view Issac.FileStorage a busca (fazer ela herdar IProdutoViewExpandida).
* Atualizar UI para permitir busca por parte do nome (Usar select e where que o Rafael explicou no paint).
* A versão SQLite ainda não terá.
